// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC884ntkT3TVa2DC6maTjM_OikVpVIElUU',
    appId: '1:558485904004:web:f1bead3c9aa35c576dc0d1',
    messagingSenderId: '558485904004',
    projectId: 'sapusenangauth',
    authDomain: 'sapusenangauth.firebaseapp.com',
    storageBucket: 'sapusenangauth.firebasestorage.app',
    measurementId: 'G-D48ZEP6EEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHl787-zihDJdHXwnjL6UovIAupMLiuvU',
    appId: '1:558485904004:android:3b37b13431ea16846dc0d1',
    messagingSenderId: '558485904004',
    projectId: 'sapusenangauth',
    storageBucket: 'sapusenangauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJyms0QEzdVE2W5nKkK-HwbvD1NRU9qCM',
    appId: '1:558485904004:ios:ce9487c77ffb08d46dc0d1',
    messagingSenderId: '558485904004',
    projectId: 'sapusenangauth',
    storageBucket: 'sapusenangauth.firebasestorage.app',
    iosBundleId: 'com.example.sapuSenang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJyms0QEzdVE2W5nKkK-HwbvD1NRU9qCM',
    appId: '1:558485904004:ios:ce9487c77ffb08d46dc0d1',
    messagingSenderId: '558485904004',
    projectId: 'sapusenangauth',
    storageBucket: 'sapusenangauth.firebasestorage.app',
    iosBundleId: 'com.example.sapuSenang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC884ntkT3TVa2DC6maTjM_OikVpVIElUU',
    appId: '1:558485904004:web:77d6a04d0a08cf796dc0d1',
    messagingSenderId: '558485904004',
    projectId: 'sapusenangauth',
    authDomain: 'sapusenangauth.firebaseapp.com',
    storageBucket: 'sapusenangauth.firebasestorage.app',
    measurementId: 'G-ZSZYY7K0SJ',
  );
}
